spring.application.name=user_management_system

# DataSource
spring.datasource.url=jdbc:mysql://localhost:3306/user_management_system?createDatabaseIfNotExist=true
spring.datasource.username=appuser
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

#Swagger
# Sort the Controllers (Tags) alphabetically
springdoc.swagger-ui.tags-sorter=alpha

# Sort the HTTP methods (GET, POST, etc.) inside each controller alphabetically
springdoc.swagger-ui.operations-sorter=method
# 1. Enable the doc generation
springdoc.api-docs.enabled=true

# 2. Tell Swagger where your API is (prevents Petstore)
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/v3/api-docs

springdoc.swagger-ui.custom-path=/webjars/swagger-ui-themes/3.0.1/themes/3.x/theme-newspaper.css